AllCops:
  Include:
    - Gemfile
    - '**/*.babl'
  TargetRubyVersion: 2.3

# Begin -- Keep the following
CaseIndentation:
    EnforcedStyle: end

ParameterLists:
    Max: 5
    CountKeywordArgs: false

Rails:
    Enabled: False

Style/AndOr:
    EnforcedStyle: conditionals

Style/BlockDelimiters:
    Enabled: False

Style/CollectionMethods:
    Enabled: True

Style/Documentation:
    Enabled: False

Style/Lambda:
    Enabled: False

Style/MultilineIfModifier:
    Enabled: False

Style/NumericLiterals:
    Enabled: False

Style/SignalException:
    EnforcedStyle: only_raise

Layout/AlignParameters:
    EnforcedStyle: with_fixed_indentation

Layout/ExtraSpacing:
    Enabled: True

Layout/IndentationWidth:
    Width: 4

Layout/IndentHash:
    EnforcedStyle: consistent

Layout/MultilineOperationIndentation:
    EnforcedStyle: indented

Layout/EmptyLineAfterMagicComment:
    Enabled: False

Layout/IndentArray:
    Enabled: False

Layout/IndentHeredoc:
    Enabled: False

Layout/MultilineMethodCallIndentation:
    Enabled: False

Lint/AmbiguousBlockAssociation:
    Enabled: False

Lint/EmptyWhen:
    Enabled: False

Lint/EndAlignment:
    Enabled: False

Lint/InheritException:
    Enabled: False

Lint/NestedMethodDefinition:
    Enabled: False

Lint/SafeNavigationChain:
    Enabled: True

Lint/UnneededSplatExpansion:
    Enabled: False

Lint/UselessAccessModifier:
    Enabled: False

Metrics/LineLength:
    Max: 130

Metrics/PerceivedComplexity:
    Max: 20

Metrics/AbcSize:
    Enabled: False
    Max: 30

Metrics/BlockLength:
    Enabled: False
    Max: 25

Metrics/ClassLength:
    Enabled: False
    Max: 200

Metrics/CyclomaticComplexity:
    Enabled: False
    Max: 10

Metrics/MethodLength:
    Enabled: False
    Max: 20

Metrics/ModuleLength:
    Enabled: False

Performance/Casecmp:
    Enabled: False

Rails/TimeZone:
    Enabled: False

Security/YAMLLoad:
    Enabled: False

Style/Alias:
    Enabled: False

Style/ConditionalAssignment:
    Enabled: False

Style/ClassVars:
    Enabled: False

Style/EmptyCaseCondition:
    Enabled: False

Style/EmptyMethod:
    Enabled: False

Style/FileName:
    Enabled: False

Style/FrozenStringLiteralComment:
    Enabled: False

Style/GuardClause:
    Enabled: False

Style/MixinGrouping:
    Enabled: False

Style/MultilineBlockChain:
    Enabled: False

Style/MultilineMemoization:
    Enabled: False

Style/FrozenStringLiteralComment:
    Enabled: True

Style/MutableConstant:
    Enabled: False

Style/NestedParenthesizedCalls:
    Enabled: False

Style/Next:
    Enabled: False

Style/NumericPredicate:
    Enabled: False

Style/ParallelAssignment:
    Enabled: False

Style/RedundantParentheses:
    Enabled: False

Style/RedundantSelf:
    Enabled: False

Style/SafeNavigation:
    Enabled: False

Style/SingleLineBlockParams:
    Enabled: False

Style/CaseEquality:
    Enabled: False

Style/StringLiterals:
    Enabled: False

Style/SymbolArray:
    Enabled: False

Style/VariableNumber:
    Enabled: False
